<?php
    $title = 'Realizar cadastro';
    $this->headTitle($title);
?>
<?php
$form->setAttribute('action', $this->url('pessoa', ['action' => 'adicionar']));
$form->prepare();

echo $this->form()->openTag($form);

$id = $this->form->get('id');
$nome = $this->form->get('nome');
$sobrenome = $this->form->get('sobrenome');
$email = $this->form->get('email');
$status = $this->form->get('status');

$nome->setAttribute('class', 'form-control');
$sobrenome->setAttribute('class', 'form-control');
$email->setAttribute('class', 'form-control');

$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');
$submit->setValue('Salvar');

?>
<div class="form-group">
    <div class="col-md-6 mt-2">
        <h5><?=$this->escapeHtml($title)?></h5>
        <hr>
    </div>
    <div class="col-md-6 mt-2">
        <p>Nome</p>
        <?=$this->formElement($nome)?>
        <?=$this->formElementErrors()->render($nome, ['class' => 'help-block'])?>
    </div>
    <div class="col-md-6 mt-2">
        <p>Sobrenome</p>
        <?=$this->formElement($sobrenome)?>
        <?=$this->formElementErrors()->render($sobrenome, ['class' => 'help-block'])?>
    </div>
    <div class="col-md-6 mt-2">
        <p>Email</p>
        <?=$this->formElement($email)?>
        <?=$this->formElementErrors()->render($email, ['class' => 'help-block'])?>
    </div>
    <div class="col-md-6 mt-4">
        <p>Ativo? <?=$this->formElement($status)?> </p>
        <?=$this->formElementErrors()->render($status, ['class' => 'help-block'])?>
    </div>
    <div class="col-md-6 mt-2">
        <?=$this->formElement($submit)?>
        <a class="btn btn-secondary ml-2" href="<?=$this->url('pessoa', ['action' => 'index'])?>">Voltar</a>
    </div>
</div>