<?php
    $title = 'Editar Pessoa';
    $this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>
<?php
$form->setAttribute('action', $this->url('pessoa', ['action' => 'editar', 'id' => $id]));
$form->prepare();

echo $this->form()->openTag($form);

$id = $this->form->get('id');
$nome = $this->form->get('nome');
$sobrenome = $this->form->get('sobrenome');
$email = $this->form->get('email');
$status = $this->form->get('status');

$nome->setAttribute('class', 'form-control');

$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');
?>
<?=$this->formElement($id)?>
<div class="form-group">
    <div class="col-md-6">
        <?=$this->formElement($nome)?>
        <?=$this->formElementErrors()->render($nome, ['class' => 'help-block'])?>
    </div>
</div>
<div class="form-group">
    <div class="col-md-6">
        <?=$this->formElement($sobrenome)?>
        <?=$this->formElementErrors()->render($sobrenome, ['class' => 'help-block'])?>
    </div>
</div>
<div class="form-group">
    <div class="col-md-6">
        <?=$this->formElement($email)?>
        <?=$this->formElementErrors()->render($email, ['class' => 'help-block'])?>
    </div>
</div>
<div class="form-group">
    <div class="col-md-6">
        <?=$this->formElement($status)?>
        <?=$this->formElementErrors()->render($status, ['class' => 'help-block'])?>
    </div>
</div>
<div>
    <?=$this->formElement($submit)?>
    <div><a href="<?=$this->url('pessoa', ['action' => 'index'])?>">voltar</a></div>
</div>