<div class="card text-white bg-dark">
    <div class="card-body">
        <h5 class="card-title">Cadastros</h5>
        <p class="card-text">
            Para se cadastrar 
            <a class="link text-white" href="/pessoa/adicionar">
                <u>clique aqui</u>
            </a>
        </p>
    </div>
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Nome</th>
                <th>Sobrenome</th>
                <th>Email</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($pessoas as $pessoa) : ?>
                <tr>
                    <td><?= $pessoa->getId() ?></td>
                    <td><?= $pessoa->getNome() ?></td>
                    <td><?= $pessoa->getSobrenome() ?></td>
                    <td><?= $pessoa->getEmail() ?></td>
                    <td><?= $pessoa->getStatus() ?></td>
                    <td>
                        <a class="btn btn-sm btn-outline-light" href="/pessoa/editar/<?= $pessoa->getId() ?>">Editar</a>
                        <a class="btn btn-sm btn-outline-light" href="/pessoa/deletar/<?= $pessoa->getId() ?>">Excluir</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>